### PR TITLE
Trying to fix login in 1.7.1-1.7.5

### LINKED ISSUE #12: Not sending packet 0x02 in 1.7.1-5
```[05:32:16 INFO] [ViaVersion]: INCOMING: HANDSHAKE 0 -> 0 [HANDSHAKE[4]] Value: PacketWrapper{packetValues=[], readableObjects=[Pair{Type|VarInt, 47}, Pair{Type|String, 192.168.1.32}, Pair{Type|Integer, 25565}, Pair{Type|VarInt, 2}], id=0}
[05:32:16 INFO]: [/192.168.1.32:48680] <-> InitialHandler has connected
[05:32:16 INFO] [ViaVersion]: INCOMING: LOGIN 0 -> 0 [LOGIN_START[4]] Value: PacketWrapper{packetValues=[], readableObjects=[], id=0}
[05:32:16 INFO] [ViaVersion]: OUTGOING: LOGIN 1 -> 1 [LOGIN_ENCRYPTION_REQUEST[4]] Value: PacketWrapper{packetValues=[], readableObjects=[Pair{Type|String, -60c ... yte, -82}], id=1}
[05:32:17 INFO] [ViaVersion]: INCOMING: LOGIN 1 -> 1 [LOGIN_ENCRYPTION_RESPONSE[4]] Value: PacketWrapper{packetValues=[], readableObjects=[Pair{Type|VarIn ... 51}], id=1}
[05:32:17 INFO] [ViaVersion]: OUTGOING: LOGIN 63 -> 63 [UNKNOWN[4]] Value: PacketWrapper{packetValues=[], readableObjects=[], id=63}
[05:32:17 INFO]: [creeper123123321|/192.168.1.32:48680] <-> ServerConnector [server1] has connected
[05:32:17 INFO]: [/192.168.1.32:48680|creeper123123321] -> UpstreamBridge has disconnected
[05:32:17 INFO]: [creeper123123321|/192.168.1.32:48680] <-> ServerConnector [server1] has disconnected```

### PR DESCRIPTION
**Pull request by creeper123123321**
Closes #12

### CODE REVIEW

**Comment by Gerrygames** [comment]
Did you take a look at the UUID Type which was written before?

**Comment by creeper123123321** [comment]
UUID Type is not working

**Comment by Gerrygames** [comment]
It is doing exactly the same thing as your REPLACE_DASHES

**Comment by Gerrygames** [comment]
I did test it and it seems to work, but it should technically do the same as the UUIDType hmm.

**Pull request merged**
